/*
 * Generate a VAPID key pair (free, self-hosted - replaces Firebase keys).
 *   node gen-keys.js
 * Prints both keys, writes .dev.vars for local wrangler dev, and prints the
 * `wrangler secret put` commands for the deployed worker.
 */
import webpush from 'web-push';
import fs from 'node:fs';

const { publicKey, privateKey } = webpush.generateVAPIDKeys();

const devVars = [
  '# Generated by gen-keys.js - local secrets for wrangler dev (gitignored)',
  `VAPID_PUBLIC_KEY=${publicKey}`,
  `VAPID_PRIVATE_KEY=${privateKey}`,
  `VAPID_SUBJECT=mailto:anuj6112008@users.noreply.github.com`,
  `SITE_URL=https://anuj6112008.github.io/ReminderKrunga/`,
  ''
].join('\n');

fs.writeFileSync(new URL('./.dev.vars', import.meta.url), devVars);

console.log('VAPID public key:  ', publicKey);
console.log('VAPID private key: ', privateKey);
console.log('');
console.log('.dev.vars written (used by `npm run dev`).');
console.log('For the deployed worker run:');
console.log('  npx wrangler secret put VAPID_PUBLIC_KEY');
console.log('  npx wrangler secret put VAPID_PRIVATE_KEY');
